### ISSUE TITLE
Marketplace release v1.2 supports PyCharm Community & Educational, but not Professional

### ISSUE THREAD

**Issue by DavidAntliff** [vitalibo/bitbake-intellij-plugin#6]
This plugin is supported for PyCharm Community and Educational, but not Professional.

Are there any barriers for adding support for PyCharm Professional? If not, can this be added, please?

**Comment by moqmar** [comment]
Thanks for noticing! That seems to be caused by https://github.com/vitalibo/bitbake-intellij-plugin/blob/master/src/main/resources/META-INF/plugin.xml#L11, according to https://plugins.jetbrains.com/docs/intellij/plugin-compatibility.html#modules-specific-to-functionality it should be `com.intellij.modules.python` instead.

Edit: just changing it doesn't build anymore, so it needs to be specified somewhere else. I'll try (probably tomorrow) whether it's maybe even possible to run this without depending on the Python plugin at all.

**Comment by fbezdeka** [comment]
python code can be injected into the .bb files, so I assume you will need it (at least for syntax highlighting?)

**Comment by moqmar** [comment]
Sure, but https://github.com/vitalibo/bitbake-intellij-plugin/blob/master/src/main/java/com/github/vitalibo/intellij/bitbake/BitBakeLanguageInjector.java#L25 just uses the syntax highlighter for ".py" files, which can also be none if none is installed - then only the shell sections would be highlighted, but one could install the plugin in e.g. WebStorm as well.

I've just tested that, and it turns out that in Python syntax highlighting works without any plugins (just no syntax completion), but the "Shell Script" plugin is actually required, otherwise causing the following error:

```
java.lang.ClassCastException: class com.intellij.openapi.fileTypes.UnknownFileType cannot be cast to class com.intellij.openapi.fileTypes.LanguageFileType (com.intellij.openapi.fileTypes.UnknownFileType and com.intellij.openapi.fileTypes.LanguageFileType are in unnamed module of loader com.intellij.util.lang.PathClassLoader @31b7dea0)
	at com.github.vitalibo.intellij.bitbake.BitBakeLanguageInjector.getLanguagesToInject(BitBakeLanguageInjector.java:20)
```

So, I'm for removing the dependency and recommending Python and Shell Script plugins to be installed when an UnknownFileType is returned.

**Comment by DavidAntliff** [comment]
> I'm for removing the dependency and recommending Python and Shell Script plugins to be installed when an UnknownFileType is returned.

I'm following with interest, and happy to test out whatever the result is.

**Comment by moqmar** [comment]
Finally got around to solve this issue with a popup notification now:

![image](https://user-images.githubusercontent.com/5559994/191734656-19fb576e-4d4f-4715-b698-b7383b34b224.png)

I'll publish that version later today.

**Comment by DavidAntliff** [comment]
Today I installed "v1.3" (no change notes) into PyCharm **Professional** successfully - thank you :)

EDIT: oh, after installing (but not before), the change notes appeared as "Fix compatibility with IDEA/PyCharm Ultimate." - weird that they didn't show up in the Marketplace before installing though. They do show now, after installation.  Probably not a big deal.
